#!/usr/bin/env python3
"""
quiz_data.py — 13 click-to-reveal quiz questions, one per numbered lecture,
each written from a real exam trap already present in the corresponding
concepts/*.md page as of the 2026-09-05 rewrite (see the "Bẫy thi" / exam
traps section of each page for the source material). Bilingual VI/EN,
matching the wiki's own convention.

This is original UI copy (not a mechanical transcription of any single
concept page), so it is authored directly here rather than generated by
md2html.py -- but every question is traceable to a specific, current
concepts/*.md section, referenced in the `source` field below for
maintainability.
"""

QUIZ = [
    {
        "lecture": 1,
        "slug": "linear-regression-model",
        "q_vi": 'Một sinh viên viết trong bài làm: "Vì F-test của mô hình có ý nghĩa thống kê (p&lt;0.05), nên mô hình này là đặc tả đúng và có thể dùng để dự báo/làm chính sách." Nhận định này có đúng không?',
        "q_en": 'A student writes: "Since the model\'s F-test is statistically significant (p&lt;0.05), the model is correctly specified and can be used for forecasting/policy." Is this correct?',
        "a_vi": "Sai. F-test tổng thể có ý nghĩa chỉ cho biết ít nhất một hệ số góc khác 0 — nó <strong>không</strong> kiểm tra đặc tả mô hình đúng hay sai, không kiểm tra các giả định OLS (A1–A5), và không đo lường độ hữu ích thực tế cho dự báo/chính sách. Tương tự, \"không bác bỏ $H_0$\" chỉ có nghĩa là dữ liệu phù hợp với $H_0$, không phải là \"đã chứng minh $H_0$ đúng\".",
        "a_en": 'Wrong. A significant overall F-test only means at least one slope coefficient is nonzero — it does <strong>not</strong> test whether the model is correctly specified, does not test the OLS assumptions (A1–A5), and does not measure real-world usefulness for forecasting/policy. Likewise, "failing to reject $H_0$" only means the data are consistent with $H_0$, not that "$H_0$ has been proven true."',
        "source": "concepts/linear-regression-model.md §10 Bẫy thi tổng hợp",
    },
    {
        "lecture": 2,
        "slug": "functional-forms",
        "q_vi": "Hồi quy $\\ln(wage)$ theo $schooling$ cho hệ số $0.02667$. Diễn giải \"mỗi năm đi học thêm làm lương tăng $0.02667\\%$\" đúng hay sai?",
        "q_en": 'A regression of $\\ln(wage)$ on $schooling$ gives coefficient $0.02667$. Is the interpretation "each extra year of schooling increases wages by $0.02667\\%$" correct?',
        "a_vi": "Sai — thiếu nhân 100. Trong dạng log-lin, hệ số hồi quy $\\ln y$ trên $X$ là một <strong>tỉ lệ (proportion)</strong>, phải nhân 100 mới ra phần trăm: $0.02667\\times100=2.667\\%$ mỗi năm đi học thêm, giữ các biến khác không đổi. Quên nhân 100 là một trong những bẫy thi phổ biến nhất của functional forms.",
        "a_en": 'Wrong — missing the ×100 step. In the log-lin form, the regression coefficient of $\\ln y$ on $X$ is a <strong>proportion</strong>, which must be multiplied by 100 to get a percentage: $0.02667\\times100=2.667\\%$ per extra year of schooling, holding other variables constant. Forgetting the ×100 is one of the most common functional-forms exam traps.',
        "source": "concepts/functional-forms.md §9 Bẫy thi tổng hợp",
    },
    {
        "lecture": 3,
        "slug": "multicollinearity",
        "q_vi": "Một nhóm biến độc lập có tương quan cặp khá thấp với nhau (dưới 0.3). Có thể kết luận chắc chắn mô hình không có vấn đề multicollinearity không?",
        "q_en": "A group of independent variables all have fairly low pairwise correlations (below 0.3) with each other. Can we conclude with certainty the model has no multicollinearity problem?",
        "a_vi": "Không. Tương quan cặp thấp chỉ là một \"dấu hiệu\" (sign), không phải \"xác nhận\" (confirmation) — vẫn có thể xảy ra <strong>multicollinear đa biến</strong> (3+ biến cùng phụ thuộc lẫn nhau) mà không cặp nào riêng lẻ lộ ra tương quan cao. Cần kiểm tra VIF, không chỉ ma trận tương quan cặp.",
        "a_en": 'No. Low pairwise correlation is only a "sign," not "confirmation" — <strong>multivariate multicollinearity</strong> (3+ variables jointly dependent on each other) can still occur without any single pair showing high correlation. VIF must be checked, not just the pairwise correlation matrix.',
        "source": "concepts/multicollinearity.md §10 Bẫy thi",
    },
    {
        "lecture": 4,
        "slug": "heteroskedasticity",
        "q_vi": "BP test bác bỏ $H_0$ (có heteroskedasticity). Hệ số hồi quy $b$ ước lượng được có còn tin cậy để diễn giải dấu và độ lớn không?",
        "q_en": "The BP test rejects $H_0$ (heteroskedasticity is present). Is the estimated coefficient $b$ still trustworthy for interpreting sign and magnitude?",
        "a_vi": "Có — đây là bẫy thi phổ biến nhất của topic. Heteroskedasticity <strong>không</strong> làm hệ số $b$ bị chệch (biased) hay mất consistency, vì tính chất này chỉ phụ thuộc A1–A3, không phụ thuộc A4. Nó chỉ làm <strong>SE/VCV/suy luận thống kê</strong> (t-test, F-test, CI) không còn đáng tin — đây là vấn đề của <em>inference</em>, không phải của <em>estimation</em>. Cách vá: dùng robust standard errors.",
        "a_en": "Yes — this is the topic's most common exam trap. Heteroskedasticity does <strong>not</strong> bias the coefficient $b$ or make it inconsistent, because that property depends only on A1–A3, not on A4. It only makes the <strong>SE/VCV/statistical inference</strong> (t-test, F-test, CI) unreliable — a problem of <em>inference</em>, not of <em>estimation</em>. The fix: use robust standard errors.",
        "source": "concepts/heteroskedasticity.md §11 Bẫy thi",
    },
    {
        "lecture": 5,
        "slug": "endogeneity-iv-regression",
        "q_vi": "Kiểm định underidentification (relevance) của instrument bị bác bỏ. Có thể kết luận luôn \"instrument đủ mạnh\" (not weak) không?",
        "q_en": 'The underidentification (relevance) test for an instrument is rejected. Can we immediately conclude the instrument is "strong enough" (not weak)?',
        "a_vi": "Không. Đây là <strong>hai kiểm định khác nhau</strong>: relevance/underidentification (instrument có tương quan khác 0 với biến nội sinh, tầng 1) và strength/weak-instrument test (tương quan đó có đủ <em>mạnh</em>, tầng 2). Bác bỏ được tầng 1 không tự động nghĩa là đã qua tầng 2 — cần kiểm tra riêng (Cragg-Donald F / Kleibergen-Paap F so với ngưỡng Stock-Yogo).",
        "a_en": "No. These are <strong>two different tests</strong>: relevance/underidentification (the instrument has nonzero correlation with the endogenous variable, tier 1) and the strength/weak-instrument test (that correlation is <em>strong enough</em>, tier 2). Rejecting tier 1 does not automatically mean tier 2 is satisfied — it must be checked separately (Cragg-Donald F / Kleibergen-Paap F against the Stock-Yogo threshold).",
        "source": "concepts/endogeneity-iv-regression.md §8 Bẫy thi",
    },
    {
        "lecture": 6,
        "slug": "fixed-random-effects-model",
        "q_vi": "Hausman test không bác bỏ $H_0$. Học viên kết luận: \"vậy Random Effects là mô hình đúng\". Đúng hay sai?",
        "q_en": 'The Hausman test fails to reject $H_0$. A student concludes: "therefore Random Effects is the correct model." Right or wrong?',
        "a_vi": "Sai cách diễn giải. \"Không bác bỏ Hausman\" chỉ có nghĩa \"không đủ bằng chứng chống lại RE\", không phải bằng chứng tuyệt đối RE \"đúng\" — cùng nguyên tắc chung về \"không bác bỏ $H_0$\" trong [[concepts/linear-regression-model]]. Ngoài ra, Hausman test chỉ hợp lệ khi FE và RE có <strong>cùng bộ regressor</strong> — nếu RE có biến bất biến thời gian mà FE không có, kiểm định không hợp lệ.",
        "a_en": '"Failing to reject Hausman" only means "insufficient evidence against RE," not absolute proof RE is "correct" — the same general principle for interpreting "failing to reject $H_0$" as in [[concepts/linear-regression-model]]. Also, the Hausman test is only valid when FE and RE share the <strong>same set of regressors</strong> — if RE has a time-invariant variable FE cannot have, the test is invalid.',
        "source": "concepts/fixed-random-effects-model.md §14 Bẫy thi tổng hợp",
    },
    {
        "lecture": 7,
        "slug": "iv-regression-panel-data",
        "q_vi": "Một biến giải thích nội sinh với $\\varepsilon_{it}$ (vi phạm A3a). Chạy Fixed Effects (FE) đã đủ để giải quyết vấn đề endogeneity này chưa?",
        "q_en": "An explanatory variable is endogenous with $\\varepsilon_{it}$ (a violation of A3a). Is running Fixed Effects (FE) alone enough to fix this endogeneity?",
        "a_vi": "Chưa. FE chỉ giải quyết <strong>A3b</strong> (tương quan với $\\alpha_i$, unobserved heterogeneity bất biến thời gian), <strong>không</strong> giải quyết A3a (tương quan với $\\varepsilon_{it}$, sai số đặc thù theo thời gian). Nếu biến giải thích nội sinh theo kiểu A3a, vẫn cần IV (FE-IV/FD-IV) dù đã dùng FE.",
        "a_en": "Not enough. FE only solves <strong>A3b</strong> (correlation with $\\alpha_i$, time-invariant unobserved heterogeneity), <strong>not</strong> A3a (correlation with $\\varepsilon_{it}$, the time-varying error). If the explanatory variable is endogenous in the A3a sense, IV (FE-IV/FD-IV) is still needed even after using FE.",
        "source": "concepts/iv-regression-panel-data.md §8 Bẫy thi",
    },
    {
        "lecture": 8,
        "slug": "dynamic-panel-data-models",
        "q_vi": "Dữ liệu panel có $T$ nhỏ và Nickell bias xuất hiện rõ ở ước lượng FE cho mô hình động. Tăng số đơn vị chéo $N$ (thêm quan sát) có giúp khắc phục Nickell bias không?",
        "q_en": "A panel dataset has small $T$ and clear Nickell bias in the FE estimate of a dynamic model. Does increasing the number of cross-sectional units $N$ (adding more observations) fix the Nickell bias?",
        "a_vi": "Không. Nickell bias là hàm của $1/T$, <strong>không liên quan đến $N$</strong> — bias không biến mất dù $N\\to\\infty$ nếu $T$ vẫn nhỏ và cố định. Đây là lý do cần các ước lượng chuyên biệt (Anderson-Hsiao, Difference/System GMM) thay vì chỉ \"thu thập thêm dữ liệu\".",
        "a_en": "No. Nickell bias is a function of $1/T$, <strong>unrelated to $N$</strong> — the bias does not vanish even as $N\\to\\infty$ if $T$ stays small and fixed. This is exactly why specialized estimators (Anderson-Hsiao, Difference/System GMM) are needed instead of simply \"collecting more data.\"",
        "source": "concepts/dynamic-panel-data-models.md §8 Bẫy thi",
    },
    {
        "lecture": 9,
        "slug": "binary-response-models",
        "q_vi": "Hồi quy Logit cho hệ số $\\hat\\beta_j = -0.0318$ trên biến giá. Có thể diễn giải trực tiếp \"tăng giá 1 đơn vị làm xác suất giảm $3.18\\%$\" không?",
        "q_en": "A Logit regression gives coefficient $\\hat\\beta_j=-0.0318$ on the price variable. Can this be interpreted directly as \"a 1-unit price increase decreases the probability by $3.18\\%$\"?",
        "a_vi": "Không — đây là lỗi phổ biến nhất của toàn Topic 7. Hệ số thô của Logit/Probit chỉ cho biết <strong>chiều</strong> (dấu) thay đổi của $P$, <strong>không cho biết độ lớn</strong>. Muốn biết độ lớn tác động lên xác suất phải tính <strong>marginal effect</strong> (qua $P(1-P)$ hoặc $\\phi(X\\beta)$, tùy giá trị $X$); muốn diễn giải qua odds thì dùng $e^{\\hat\\beta_j}$ — và ngay cả khi đó, đó vẫn là phát biểu về odds, không phải % thay đổi xác suất trực tiếp.",
        "a_en": "No — this is the single most common mistake in all of Topic 7. A raw Logit/Probit coefficient only tells you the <strong>direction</strong> (sign) of the change in $P$, <strong>not the magnitude</strong>. To know the magnitude of the effect on probability you must compute the <strong>marginal effect</strong> (via $P(1-P)$ or $\\phi(X\\beta)$, depending on the value of $X$); to interpret via odds, use $e^{\\hat\\beta_j}$ — and even then that is a statement about odds, not a direct percentage change in probability.",
        "source": "concepts/binary-response-models.md §14 Bẫy thi",
    },
    {
        "lecture": 10,
        "slug": "multinomial-logit-model",
        "q_vi": "Trong mô hình MNL, hệ số $\\beta_j$ của base category luôn \"bằng 0 theo định nghĩa\". Có thể kết luận base category \"không bị ảnh hưởng gì\" bởi $X$ không?",
        "q_en": 'In an MNL model, the base category\'s coefficient $\\beta_j$ is "0 by definition." Can we conclude the base category is "unaffected" by $X$?',
        "a_vi": "Sai. Dù hệ số của base category quy ước bằng 0, <strong>marginal effect</strong> trên $P(\\text{base category})$ thường <strong>khác 0</strong> — trong case study của bài, đây thậm chí còn là marginal effect <strong>lớn nhất</strong> trong tất cả các phạm trù. $\\beta_j$ chỉ đo log-odds <em>so với base category</em>, không phải thay đổi trực tiếp của $P(Y=j)$.",
        "a_en": 'Wrong. Even though the base category\'s coefficient is conventionally 0, the <strong>marginal effect</strong> on $P(\\text{base category})$ is usually <strong>nonzero</strong> — in the case study, it is even the <strong>largest</strong> marginal effect of all categories. $\\beta_j$ only measures log-odds <em>relative to the base category</em>, not a direct change in $P(Y=j)$.',
        "source": "concepts/multinomial-logit-model.md §11 Bẫy thi",
    },
    {
        "lecture": 11,
        "slug": "ordinal-response-models",
        "q_vi": "Biến `age` có $\\hat\\beta$ dương duy nhất trong mô hình ordered logit. Có thể kỳ vọng marginal effect của `age` mang cùng một dấu ở mọi phạm trù ($k=1,\\dots,J$) không?",
        "q_en": "The variable `age` has a single positive $\\hat\\beta$ in an ordered logit model. Can we expect `age`'s marginal effect to carry the same sign across every category ($k=1,\\dots,J$)?",
        "a_vi": "Không. Dù $\\beta$ chỉ có một dấu duy nhất (tác động lên biến tiềm ẩn $y^*$), marginal effect trên từng $Pr(y=k)$ có thể khác dấu nhau giữa các phạm trù — ví dụ số của `age` cho thấy marginal effect có thể <strong>dương</strong> ở phạm trù thấp nhất và <strong>âm</strong> ở phạm trù giữa/cao. Quy tắc chung: tổng marginal effect của một biến trên tất cả các phạm trù luôn xấp xỉ 0.",
        "a_en": "No. Even though $\\beta$ has only one sign (its effect on the latent variable $y^*$), the marginal effect on each $Pr(y=k)$ can differ in sign across categories — the numerical example for `age` shows the marginal effect can be <strong>positive</strong> at the lowest category and <strong>negative</strong> at the middle/higher categories. General rule: a variable's marginal effects summed across all categories always approximate 0.",
        "source": "concepts/ordinal-response-models.md §11 Bẫy thi tổng hợp",
    },
    {
        "lecture": 12,
        "slug": "count-data-models",
        "q_vi": "Kiểm định joint significance của nhóm biến `risk` bằng Poisson cho $p=0.048$ (bác bỏ $H_0$), nhưng bằng Negative Binomial (NB) cho $p\\approx0.2$ (không bác bỏ). Vì sao hai mô hình lại cho kết luận trái ngược nhau?",
        "q_en": "A joint significance test of the `risk` group of variables gives $p=0.048$ (reject $H_0$) under Poisson, but $p\\approx0.2$ (fail to reject) under Negative Binomial (NB). Why do the two models give opposite conclusions?",
        "a_vi": "Vì dữ liệu có <strong>overdispersion</strong> mà Poisson không kiểm tra trước khi dùng. Khi có overdispersion, SE của Poisson bị <strong>đánh giá thấp một cách hệ thống</strong>, khiến kết luận về ý nghĩa thống kê bị thổi phồng sai. NB xử lý overdispersion đúng cách nên cho kết luận đáng tin hơn trong trường hợp này — bài học: luôn kiểm tra overdispersion trước khi dùng Poisson.",
        "a_en": "Because the data has <strong>overdispersion</strong> that Poisson does not check for before being used. Under overdispersion, Poisson's SE is <strong>systematically underestimated</strong>, inflating significance conclusions incorrectly. NB handles overdispersion properly, so it gives the more trustworthy conclusion here — the lesson: always check for overdispersion before using Poisson.",
        "source": "concepts/count-data-models.md §12 Bẫy thi tổng hợp",
    },
    {
        "lecture": 13,
        "slug": "censored-regression-tobit",
        "q_vi": "Một câu hỏi nghiên cứu chỉ hỏi về hiệu ứng \"trong số những người đã có dư nợ ($y>0$)\". Nên dùng Unconditional marginal effect hay Conditional marginal effect của Tobit?",
        "q_en": 'A research question only asks about the effect "among those who already have a positive balance ($y>0$)." Should the Tobit\'s Unconditional or Conditional marginal effect be used?',
        "a_vi": "Conditional ME. Từ khóa \"trong số những người đã...\" / \"biết rằng $y>0$\" báo hiệu cần <strong>Conditional ME</strong>, không phải Unconditional ME (dành cho câu hỏi về hiệu ứng trung bình trên <em>toàn bộ</em> mẫu/dân số). Dùng nhầm loại là \"bẫy lớn nhất\" của topic — bên cạnh đó, tuyệt đối không dùng thẳng $\\beta$ (hiệu ứng trên biến latent $y^*$) để trả lời câu hỏi về hiệu ứng lên $y$ quan sát được.",
        "a_en": 'Conditional ME. The phrase "among those who already..." / "given that $y>0$" signals the <strong>Conditional ME</strong> is needed, not the Unconditional ME (which answers questions about the average effect over the <em>entire</em> sample/population). Using the wrong type is the topic\'s "biggest trap" — relatedly, never use the raw $\\beta$ (the effect on the latent variable $y^*$) to answer a question about the effect on the observed $y$.',
        "source": "concepts/censored-regression-tobit.md §9 Bẫy thi tổng hợp — mở rộng",
    },
]

assert len(QUIZ) == 13
assert sorted(q["lecture"] for q in QUIZ) == list(range(1, 14))
